name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (with Shade plugin)
        run: mvn -B clean package shade:shade

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: FacultyFeedbackApp
          path: target/*-shaded.jar
